export const SET_LOADING_STATE = "SET_LOADING_STATE";

export const LOAD_SNAPSHOT_PENDING = "LOAD_SNAPSHOT_PENDING";
export const LOAD_SNAPSHOT_SUCCESS = "LOAD_SNAPSHOT_SUCCESS";
export const LOAD_SNAPSHOT_FAILED = "LOAD_SNAPSHOT_FAILED";